### ISSUE TITLE
possible to have an accessory per spotify device?

### ISSUE THREAD

**Issue by pponce** [scholtzan/homebridge-rusty-spotify#2]
Awesome plugin!
Wanted to know if i could create an accessory per spotify device.
Also noticed that the generate_config file i believe uses the wrong accessory name for the config.
I got an error about the there not being a plugin for the accessory when i first ran it.  After i changed the accessory value to Spotify in the config things worked fine.
edited output 
                "accessory": "Spotify",
                "name": "SpotifyAccessory",
generate_config output
                "accessory": "SpotifyAccessory",
                "name": "SpotifyAccessory",

**Comment by scholtzan** [comment]
Thanks, I fixed the script.

That's definitely an interesting idea! One issue I noticed is that devices go into an inactive state and disconnect from the Spotify API if music is paused on them for a while. So, if it can happen that in order to start playing music on a device, some devices need to be manually activated again (e.g. by opening Spotify on them).

I'll keep the issue open and will pick it up when I have some more time to work on that.

**Comment by mrkita** [comment]
This would be awesome, I was hoping to just have one accessory per device, and call out which one I want to turn on. Doesn't seem to work as the accessory name is hard coded. How hard would this be?

**Comment by scholtzan** [comment]
I just pushed a new version (0.4.0) of the plugin that will automatically discover available Spotify devices and add them as accessories. 

The configuration for the plugin has changed slightly.

Now it's:

```json
{
    "platform": "Spotify",   // before this was "accessory": "Spotify"
    "name": "Spotify",
    "client_id": "<client_id>",
    "client_secret": "<client_secret>",
    "refresh_token": "<refresh_token>"
  }
```

**Comment by moshed** [comment]
@scholtzan is this still supposed to go under the accessories value in the JSON?

when I put it in there my entire homebridge server hangs when starting

**Comment by scholtzan** [comment]
It needs to go under `platforms` now. I'll update the README.
